server/config/routes.rb
Rails.application.routes.draw do
  get 'static/:id/show' => 'static#show', as: :static

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'labs#index'

  resources :labs
  resources :users
  resources :assignments

  get 'assignments/:id/grades' => 'assignments#grades', as: :assignments_grades
  get 'labs/:id/grades' => 'labs#grades', as: :labs_grades
  post 'labs/:id/toggle_hidden' => 'labs#toggle_hidden', as: :labs_toggle_hidden

  post 'assignments/testCode'
  post 'assignments/saveCode'
  post 'assignments/restartCode'
  post 'assignments/uploadCode'
  post 'assignments/downloadCode'
  post 'assignments/submitCode'
  post 'assignments/revertCodeToSaved'

end

server/app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :lab
  has_many :grades, :dependent => :destroy

  def getPath
    File.join(AssignmentsHelper.assignments_path, getDirectoryName())
  end

  def getTestFilePath
    File.join(getPath, 'tests.cpp')
  end

  def getSpecFilePath
    File.join(getPath, 'spec.cpp')
  end

  def getSpecFileContents
    begin
      spec_file = File.open(getSpecFilePath())
      spec_file_contents = spec_file.read
    rescue Errno::ENOENT
      # We should probably fill with a default spec file here.
      spec_file_contents = ""
    end

    return spec_file_contents
  end

  def hasSpecFile?
    FileTest.exists?(getSpecFilePath())
  end

  def getDirectoryName
    sanitizeFilename(name)
  end

  def getFileName
    "solution.cpp"
  end

  def sanitizeFilename(filename)
    # Split the name when finding a period which is preceded by some
    # character, and is followed by some character other than a period,
    # if there is no following period that is followed by something
    # other than a period (yeah, confusing, I know)
    fn = filename.split /(?<=.)\.(?=[^.])(?!.*\.[^.])/m

    # We now have one or two parts (depending on whether we could find
    # a suitable period). For each of these parts, replace any unwanted
    # sequence of characters with an underscore
    fn.map! { |s| s.gsub /[^a-z0-9\-]+/i, '_' }

    # Join the parts with a period and return the result
    fn = fn.join '.'

    # Finally, return the lowercased version
    return fn.downcase
  end
end

server/app/controllers/assignments_controller.rb
require 'fileutils'
require 'assignment_grader'

class AssignmentsController < ApplicationController
  load_and_authorize_resource
  before_action :set_assignment, only: [:show, :edit, :update, :destroy, :testCode, :saveCode, :restartCode, :uploadCode, :downloadCode, :Code, :revertCodeToSaved]

  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = Assignment.all
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
    if (!current_user.hasSolutionFileForAssignment?(@assignment))
      to_write_solution = ""
      if @assignment.hasSpecFile?
        to_write_solution = @assignment.getSpecFileContents()
      end

      current_user.writeToSolutionFileForAssignment(@assignment, to_write_solution)
    end

    @editor_file_contents = current_user.getSolutionFileContentsForAssignment(@assignment)
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
    @labs = Lab.all
  end

  # GET /assignments/1/edit
  def edit
    @labs = Lab.all
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(assignment_params)
    @labs = Lab.all

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :new }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1
  # PATCH/PUT /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to assignments_url, notice: 'Assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def grades
    set_assignment
  end

  def testCode
    # Runs the unit test tool with the users code (what is in the editor right now, not what is saved)

    assignment_grader = AssignmentGrader.new(@assignment, params[:editor_text])
    assignment_grader.runTests()

    render json: {:progress_bar_html => assignment_grader.getProgressBarHTML()}
  end

  def submitCode
    assignment_grader = AssignmentGrader.new(@assignment, params[:editor_text])
    assignment_grader.runTests()

    # dummy score until actual score can be found
    score = assignment_grader.getGrade()
    # find or create a grade for the assignment/user combination
    new_grade = Grade.where(:user => current_user, :assignment => @assignment).first_or_create

    # only update score if it's higher than the existing one
    if new_grade.score.nil? || new_grade.score < score
      new_grade.score = score
      new_grade.save
    end

    render json: {:progress_bar_html => assignment_grader.getProgressBarHTML()}
  end

  def saveCode
    # Saves the user's code to their solution file
    editor_text = params[:editor_text]

    current_user.writeToSolutionFileForAssignment(@assignment, editor_text)

    render nothing: true
  end

  def restartCode
    # Restarts the code to the default spec, does not save it to the user's solution file
    render json: {:new_editor_content => @assignment.getSpecFileContents()}
  end

  def revertCodeToSaved
    # Restarts the code to their saved file
    render json: {:new_editor_content => current_user.getSolutionFileContentsForAssignment(@assignment)}

  end

  def uploadCode
    # Uploads the file received and replaces the user's solution file with it.
    uploaded_file = params[:assignment_file]
    assignment_file_path = current_user.getSolutionFilepathForAssignment(@assignment)

    upload_success = false
    if uploaded_file
      uploaded_file_contents = uploaded_file.read
      uploaded_file_contents = uploaded_file_contents.force_encoding('utf-8')

      if (uploaded_file_contents.valid_encoding?)
        begin
          current_user.writeToSolutionFileForAssignment(@assignment, uploaded_file_contents)
          upload_success = true
        rescue
          upload_success = false
        end
      else
        upload_success = false
      end
    end

    respond_to do |format|
      if upload_success
        format.html {
          redirect_to @assignment,
          :flash => {
            :success => 'Assignment file was successfully uploaded.'
          }
        }
      else
        format.html {
          redirect_to @assignment,
          :flash => {
            :error => 'There was a problem uploading your assignment file.'
          }
        }
      end
    end
  end

  def downloadCode
    # Downloads the code that the user has saved, if any.

    # If the user wants to save their code
    if (params["commit"] == "Yes")
      editor_text = params["editor-text-hidden"]
      current_user.writeToSolutionFileForAssignment(@assignment, editor_text)
    end

    puts params

    if current_user.hasSolutionFileForAssignment?(@assignment)
      send_file(current_user.getSolutionFilepathForAssignment(@assignment))
    else
      respond_to do |format|
        format.html {
          redirect_to @assignment,
          :flash => {
            :error => 'No assignment file to download. Please save your code and try again.'
          }
        }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_assignment
    @assignment = Assignment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def assignment_params
    params.require(:assignment).permit(:description, :name)
  end
end

server/app/helpers/assignments_helper.rb
module AssignmentsHelper
  def self.testing_tool_path
    File.join(TEST_TOOL_CONFIG["home_path"],
    TEST_TOOL_CONFIG["testing_tool_relative_path"])
  end

  def self.assignments_path
    File.join(TEST_TOOL_CONFIG["home_path"],
    TEST_TOOL_CONFIG["assignments_relative_path"])
  end

  def self.users_path
    File.join(TEST_TOOL_CONFIG["home_path"],
    TEST_TOOL_CONFIG["users_relative_path"])
  end

  def self.common_path
    File.join(TEST_TOOL_CONFIG["home_path"],
    TEST_TOOL_CONFIG["common_relative_path"])
  end

  def self.testing_tool_script
    File.join(TEST_TOOL_CONFIG["home_path"],
    TEST_TOOL_CONFIG["testing_tool_script"])
  end

  def self.ruby_executable
    TEST_TOOL_CONFIG["ruby_executable"]
  end

  def self.getEditorText(user, assignment)
    if (user.hasSolutionFileForAssignment?(assignment))
      return user.getSolutionFileContentsForAssignment(assignment)
    elsif assignment.hasSpecFile?
      return assignment.getSpecFileContents()
    else
      return ""
    end
  end

  def bootstrap_class_for(flash_type)
    case flash_type
    when "success"
      "alert-success"
    when "error"
      "alert-danger"
    when "alert"
      "alert-warning"
    when "notice"
      "alert-info"
    else
      flash_type.to_s
    end
  end

end

server/app/views/assignments/_description_panel.html.erb
<div id="descriptionPanel" class="panel panel-default" >

  <div class="panel-heading">
    <h3 class="panel-title"><%= @assignment.name %></h3>
  </div>
  <div class="panel-body" >

    <div id="description">
      <%= @assignment.description.html_safe %>
    </div>

    <div class="btn-group btn-group-justified" role="group" aria-label="...">
      <div class="btn-group" role="group" id="test_btn">
        <button type="button" class="btn btn-default" data-toggle="tooltip" title="Test if your code works">Test</button>
      </div>
      <div class="btn-group" role="group" id="submit_btn">
        <button type="button" class="btn btn-default" data-toggle="tooltip" title="Submit your code to be graded" data-container="body">Submit</button>
      </div>
    </div>
  </div>
</div>

server/app/views/assignments/_download_modal.html.erb
<div class="modal fade" id="download_modal" role="dialog">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close modal-close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Download Code</h4>
      </div>
      <div class="modal-body">
        <p>This will only download the code you have saved. Would you like to save your code first?</p>
      </div>
      <div class="modal-footer">
        <%= form_tag({:action => "downloadCode", :id => @assignment.id}, :multipart => true, :method => 'post') do%>
        <%= hidden_field_tag 'editor-text-hidden'%>
        <%= submit_tag("Yes", :class => "btn btn-success", :id => "btn-download-yes") %>
        <%= submit_tag("No", :class => "btn btn-danger", :id => "btn-download-no") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

server/app/views/assignments/_editor_header_buttons.html.erb
<div id="header-button-container">
  <div class="btn-group btn-group-justified" id="editor-btn-group" role="group" aria-label="...">
    <div class="btn-group" role="group">
      <span>
        <button type="button" id="btn-restart" class="btn btn-default btn-sm btn-editor-header" data-toggle="tooltip" data-placement="bottom" title="Reset">
          <span class="glyphicon glyphicon-file"></span>
        </button>
      </span>
    </div>
    <div class="btn-group" role="group">
      <span>
        <button type="button" id="btn-revert-to-saved" class="btn btn-default btn-sm btn-editor-header" data-toggle="tooltip" data-placement="bottom" title="Revert">
          <span class="glyphicon glyphicon-refresh"></span>
        </button>
      </span>
    </div>
    <div class="btn-group" role="group">
      <span>
        <button type="button" id="btn-save" class="btn btn-default btn-sm btn-editor-header" data-toggle="tooltip" data-placement="bottom" title="Save">
          <span class="glyphicon glyphicon-floppy-save"></span>
        </button>
      </span>
    </div>
    <div class="btn-group" role="group">
      <span data-toggle="modal" data-target="#upload_modal">
        <button type="button" id="btn-upload" class="btn btn-default btn-sm btn-editor-header" data-toggle="tooltip" data-placement="bottom" title="Upload">
          <span class="glyphicon glyphicon-cloud-upload"></span>
        </button>
      </span>
    </div>
    <div class="btn-group" role="group">
      <span data-toggle="modal" data-target="#download_modal">
        <button type="button" id="btn-download" class="btn btn-default btn-sm btn-editor-header" data-toggle="tooltip" data-placement="bottom" title="Download">
        <span class="glyphicon glyphicon-cloud-download"></span>
        </button>
      </span>
    </div>
  </div>
</div>

server/app/views/assignments/_editor_panel.html.erb
<div id="editorPanel" class="panel panel-default" >
  <div class="panel-heading">
    <h3 class="panel-title">Editor</h3>

    <%= render 'editor_header_buttons' %>

  </div>
  <div class="panel-body" id="editor-panel-body">
    <div id="editor"><%= @editor_file_contents %></div>
  </div>
</div>

server/app/views/assignments/_flash_messages.html.erb
<div id="status_div">
  <% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <%= message %>
  </div>
  <% end %>
</div>

server/app/views/assignments/_form.html.erb
<%= form_for(@assignment) do |f| %>
  <% if @assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% @assignment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :lab %><br>
    <%= f.collection_select :id, @labs, :id, :name, include_blank: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/assignments/_script.html.erb
<script>

var close_requests = 0;

function fillHiddenEditorText() {
  $('#editor-text-hidden').val(getEditorContents());
}

function getEditorContents() {
  return editor.getValue();
}

function stopResizing() {
  $('#editor').stop();
  $('#descriptionPanel').stop();
  $('#description').stop();
}

function resizeToSmaller() {
  stopResizing();
  $('#editor').height($(window).height() - 287);
  $('#descriptionPanel').height($(window).height() - 250);
  $('#description').height($(window).height() - 360);
}

function resizeToFull() {
  stopResizing();
  $('#editor').height($(window).height() - 227);
  $('#descriptionPanel').height($(window).height() - 190);
  $('#description').height($(window).height() - 300);
}

function resizeToFullAnimated() {
  stopResizing();
  $('#editor').animate({height:$(window).height() - 227}, 500);
  $('#descriptionPanel').animate({height:$(window).height() - 190}, 500);
  $('#description').animate({height:$(window).height() - 300}, 500);
}

function getAnimatedProgressBar() {
  return '<div class="progress-bar progress-bar-striped active progress-bar-testing" role="progressbar">Running Tests</div>';
}

function getServerErrorProgressBar() {
  return '<div class="progress-bar progress-bar-error" role="progressbar">Server Error</div>';
}

// message can be whatever
// alert_class must be one of:
//    alert-success
//    alert-info
//    alert-warning
//    alert-danger
function buildAlertBox(message, alert_class) {
  resizeToSmaller();
  autoCloseAlert();

  return '<div class="alert ' + alert_class + ' fade in">' + message + '</div>'
}

function buildAlertBoxSuccess(message) {
  return buildAlertBox(message, "alert-success");
}

function buildAlertBoxInfo(message) {
  return buildAlertBox(message, "alert-info");
}

function buildAlertBoxWarning(message) {
  return buildAlertBox(message, "alert-warning");
}

function buildAlertBoxDanger(message) {
  return buildAlertBox(message, "alert-danger");
}

function hasAlert() {
  return $('.alert').length == 1;
}

function requestClose() {
  close_requests++;
}

function suppressRequest() {
  close_requests--;
}

function shouldClose() {
  return close_requests == 1;
}

function closeAlert() {
  if (shouldClose()) {
    resizeToFullAnimated();
    $(".alert").slideUp(500, function(){
      $(this).remove();
    });
  }
  suppressRequest();
}

function autoCloseAlert() {
  requestClose();
  window.setTimeout(function() {
    closeAlert();
  }, 2000);
}

var editor = ace.edit("editor");
editor.$blockScrolling = Infinity;

$( document ).ready(function() {
  if (hasAlert()) {
    is_full_size = false;
  } else {
    is_full_size = true;
  }

  //listen for changes
  $(window).resize(function() {
    if (hasAlert()) {
      resizeToSmaller();
    } else {
      resizeToFull();
    }
  });

  //set initially
  if (hasAlert()) {
    autoCloseAlert();
    resizeToSmaller();
  } else {
    resizeToFull();
  }

  editor.setTheme("ace/theme/chrome");
  editor.getSession().setMode("ace/mode/c_cpp");

  $('[data-toggle="tooltip"]').tooltip();

});

$('#test_btn').on('click', function() {
  $('#progress_bar_container').html(getAnimatedProgressBar());

  $.ajax({
    type: 'post',
    url: 'testCode',
    data: {editor_text:getEditorContents(),id:<%=@assignment.id%>},
    success: function(response) {
      // Load the progress bar with the html from the response
      $('#progress_bar_container').html(response.progress_bar_html);
      // Enable popovers
      $('[data-toggle="popover"]').popover();
    },
    error: function(jqXHR, textStatus, errorThrown) {
      $('#progress_bar_container').html(getServerErrorProgressBar());
    }
  });
  return false;
});

$('#submit_btn').on('click', function() {
  $('#progress_bar_container').html(getAnimatedProgressBar());

  $.ajax({
    type: 'post',
    url: 'submitCode',
    data: {editor_text:getEditorContents(),id:<%=@assignment.id%>},
    success: function(response) {
      // Load the progress bar with the html from the response
      $('#progress_bar_container').html(response.progress_bar_html);
      // Enable popovers
      $('[data-toggle="popover"]').popover();
    },
    error: function(jqXHR, textStatus, errorThrown) {
      $('#progress_bar_container').html(getServerErrorProgressBar());
    }
  });
  return false;
});

$('#btn-save').on('click', function() {
  $.ajax({
    type: 'post',
    url: 'saveCode',
    data: {editor_text:getEditorContents(),id:<%=@assignment.id%>},
    success: function(response) {
      $('#status_div').html(buildAlertBox("File saved successfully!", "alert-success"));
    }
  });
});

$('#btn-restart').on('click', function() {
  $.ajax({
    type: 'post',
    url: 'restartCode',
    data: {editor_text:getEditorContents(),id:<%=@assignment.id%>},
    success: function(response) {
      $('#status_div').html(buildAlertBox("Reset file to the default spec.", "alert-success"));
      editor.setValue(response.new_editor_content, -1);
    }
  });
});

$('#btn-download').on('click', function() {
  fillHiddenEditorText();
});

$('#btn-download-yes').on('click', function() {
  $('#download_modal').modal('hide');
});

$('#btn-download-no').on('click', function() {
  $('#download_modal').modal('hide');
});

</script>

server/app/views/assignments/_test_code_script.html.erb
<script>
function getAnimatedProgressBar() {
  return '<div class="progress-bar progress-bar-striped active progress-bar-testing" role="progressbar">Running Tests</div>';
}

function getServerErrorProgressBar() {
  return '<div class="progress-bar progress-bar-error" role="progressbar">Server Error</div>';
}

$('#test_btn').on('click', function() {
  $('#progress_bar_container').html(getAnimatedProgressBar());

  $.ajax({
    type: 'post',
    url: 'testCode',
    data: {editor_text:getEditorContents(),id:<%=@assignment.id%>},
    success: function(response) {
      // Load the progress bar with the html from the response
      $('#progress_bar_container').html(response.progress_bar_html);
      // Enable popovers
      $('[data-toggle="popover"]').popover();
    },
    error: function(jqXHR, textStatus, errorThrown) {
      $('#progress_bar_container').html(getServerErrorProgressBar());
    }
  });
  return false;
});

$('#submit_btn').on('click', function() {
  $('#progress_bar_container').html(getAnimatedProgressBar());

  $.ajax({
    type: 'post',
    url: 'submitCode',
    data: {editor_text:getEditorContents(),id:<%=@assignment.id%>},
    success: function(response) {
      // Load the progress bar with the html from the response
      $('#progress_bar_container').html(response.progress_bar_html);
      // Enable popovers
      $('[data-toggle="popover"]').popover();

      // Show the user that it submitted successfully
      $('#status_div').html(buildAlertBox("Code submitted for grading!", "alert-success"));

    },
    error: function(jqXHR, textStatus, errorThrown) {
      $('#progress_bar_container').html(getServerErrorProgressBar());

      // Show the user that it submitted successfully
      $('#status_div').html(buildAlertBox("An error occurred while submitting your code.", "alert-danger"));
    }
  });
  return false;
});

function generateModalFor(element) {
  $("#test-results-title").html($(element).find('.error-title').html());
  $("#test-results-body").html($(element).find('.failure-message-full').html());
}

// Have to use this because the progress bars have a data toggle already
$(document).on("click", ".progress-bar-clickable", function() {
  generateModalFor(this);

  $('.popover').hide();
  $('#test-results-modal').modal('show');
});

</script>

server/app/views/assignments/_test_results_modal.html.erb
<div class="modal fade" id="test-results-modal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close modal-close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" id="test-results-title">Some error</h4>
      </div>
      <div class="modal-body" id="test-results-body">
        <p>Test modal</p>
      </div>
    </div>
  </div>
</div>

server/app/views/assignments/_upload_modal.html.erb
<div class="modal fade" id="upload_modal" role="dialog">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close modal-close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Upload Code</h4>
      </div>
      <div class="modal-body">
        <p> This will overwrite any code you have saved. </p>
        <%= form_tag({:action => "uploadCode", :id => @assignment.id}, :multipart => true, :method => 'post') do %>
        <span class="input-group">
          <span class="btn btn-info btn-file input-group-btn" style="border-top-right-radius: 0px;border-bottom-right-radius: 0px;font-size: 14px;">
            Browse
            <%= file_field_tag('assignment_file', :class => 'btn btn-info', onchange: "$(this).parent().parent().find('.form-control').html($(this).val().split(/[\\\\|/]/).pop());") %>
          </span>
          <span class="form-control" id="form-file-name">
            <span id="default-filler">Select a file</span>
          </span>
        </span>
      </div>
      <div class="modal-footer">
        <%= submit_tag("Upload", :class => "btn btn-success") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

server/app/views/assignments/edit.html.erb
<h1>Editing Assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>

server/app/views/assignments/grades.html.erb
<h2><%= @assignment.name %> Grades</h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>MultiPass</th>
      <th>Score</th>
      <th>Submitted</th>
    </tr>
  </thead>

  <tbody>
    <% @assignment.grades.each do |grade| %>
    <tr>
      <td><%= link_to grade.user.name, grade.user, class: "btn btn-default btn-xs" %></td>
      <td><%= grade.user.multipass_id %></td>
      <td><%= grade.score %></td>
      <td><%= grade.updated_at.localtime %></td>
    </tr>
    <% end %>
  </tbody>
</table>

server/app/views/assignments/new.html.erb
<h1>New Assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', assignments_path %>

server/app/views/assignments/show.html.erb
<div class="row" >
  <% provide(:title, @assignment.name) %>
  <div class="row" style="height: 500px;">
    <div class="col-md-12">
      <%= render 'flash_messages' %>
      <div>
        <h4 class="pull-left">Test Results</h4>
        <div class="btn-group pull-right">
          <% if current_user.role == "admin" %>
            <%= link_to 'Edit', rails_admin.edit_path(model_name: 'assignment', id: @assignment.id), class: "btn btn-danger" %>
          <% end %>
          <% if can? :grades, @assignment %>
            <%= link_to 'View Grades', assignments_grades_path, class: "btn btn-danger" %>
          <% end %>
        </div>
      </div>
      <div class="clearfix"></div>
      <div id="progress_bar_container" class="progress progress-bar-segmented">
      </div>
    </div>

    <div class="col-md-4">
      <%= render 'description_panel' %>
    </div>

    <div class="col-md-8">
      <%= render 'editor_panel' %>
    </div>
  </div>
</div>

<div id="modal-container">
  <%= render 'upload_modal' %>
  <%= render 'download_modal' %>
  <%= render 'test_results_modal' %>
</div>

<%= render 'main_script' %>
<%= render 'test_code_script' %>