server/config/routes.rb
Rails.application.routes.draw do
  get 'static/:id/show' => 'static#show', as: :static

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'labs#index'

  resources :labs
  resources :users
  resources :assignments

  get 'assignments/:id/grades' => 'assignments#grades', as: :assignments_grades
  get 'labs/:id/grades' => 'labs#grades', as: :labs_grades
  post 'labs/:id/toggle_hidden' => 'labs#toggle_hidden', as: :labs_toggle_hidden

  post 'assignments/testCode'
  post 'assignments/saveCode'
  post 'assignments/restartCode'
  post 'assignments/uploadCode'
  post 'assignments/downloadCode'
  post 'assignments/submitCode'
  post 'assignments/revertCodeToSaved'

end

server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <img src="/mines.png" alt="mines", class="pull-left" id="logo-image"/>
      <%= link_to "AutoGrader", root_path, class: "navbar-brand" %>
    </div>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? && current_user.role == "admin" %>
          <li><%= link_to "Admin", rails_admin_path %></li>
        <% end %>
	<% unless @statics.nil? %>
        <% @statics.each do |static| %>
          <li><%= link_to static.name, static %></li>
        <% end %>
	<% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= current_user.name %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to('Grades', current_user) %></li>
              <li><%= link_to('Preferences', [:edit, current_user]) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to('Login', new_user_session_path) %> </li>
        <% end %>
        </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



<div class="container">
	<%= yield %>
<div>

</body>
</html>