server/config/routes.rb
Rails.application.routes.draw do
  get 'static/:id/show' => 'static#show', as: :static

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'labs#index'

  resources :labs
  resources :users
  resources :assignments

  get 'assignments/:id/grades' => 'assignments#grades', as: :assignments_grades
  get 'labs/:id/grades' => 'labs#grades', as: :labs_grades
  post 'labs/:id/toggle_hidden' => 'labs#toggle_hidden', as: :labs_toggle_hidden

  post 'assignments/testCode'
  post 'assignments/saveCode'
  post 'assignments/restartCode'
  post 'assignments/uploadCode'
  post 'assignments/downloadCode'
  post 'assignments/submitCode'
  post 'assignments/revertCodeToSaved'

end

server/app/models/lab.rb
class Lab < ActiveRecord::Base
  has_many :assignments
end

server/app/controllers/labs_controller.rb
class LabsController < ApplicationController
  load_and_authorize_resource
  before_action :set_lab, only: [:show, :edit, :update, :destroy]

  # GET /labs
  # GET /labs.json
  def index
    @labs = Lab.all
  end

  # GET /labs/1
  # GET /labs/1.json
  def show
  end

  # GET /labs/new
  def new
    @lab = Lab.new
  end

  # GET /labs/1/edit
  def edit
  end

  # POST /labs
  # POST /labs.json
  def create
    @lab = Lab.new(lab_params)

    respond_to do |format|
      if @lab.save
        format.html { redirect_to @lab, notice: 'Lab was successfully created.' }
        format.json { render :show, status: :created, location: @lab }
      else
        format.html { render :new }
        format.json { render json: @lab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labs/1
  # PATCH/PUT /labs/1.json
  def update
    respond_to do |format|
      if @lab.update(lab_params)
        format.html { redirect_to @lab, notice: 'Lab was successfully updated.' }
        format.json { render :show, status: :ok, location: @lab }
      else
        format.html { render :edit }
        format.json { render json: @lab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labs/1
  # DELETE /labs/1.json
  def destroy
    @lab.destroy
    respond_to do |format|
      format.html { redirect_to labs_url, notice: 'Lab was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_hidden
    @lab.hidden = !@lab.hidden
    @lab.save
    redirect_to @lab
  end

  def grades
    set_lab
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lab
      @lab = Lab.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lab_params
      params.require(:lab).permit(:name)
    end
end

server/app/helpers/labs_helper.rb
module LabsHelper
end

server/app/views/labs/_form.html.erb
<%= form_for(@lab) do |f| %>
  <% if @lab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lab.errors.count, "error") %> prohibited this lab from being saved:</h2>

      <ul>
      <% @lab.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/labs/edit.html.erb
<h1>Editing Lab</h1>

<%= render 'form' %>

<%= link_to 'Show', @lab %> |
<%= link_to 'Back', labs_path %>

server/app/views/labs/grades.html.erb
<h2><%= @lab.name %> Grades</h2>

<% @lab.assignments.each do |assignment| %>
<h4><%= link_to assignment.name, assignment%></h4>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>MultiPass</th>
      <th>Score</th>
      <th>Submitted</th>
    </tr>
  </thead>

  <tbody>
    <% assignment.grades.each do |grade| %>
    <tr>
      <td><%= link_to grade.user.name, grade.user, class: "btn btn-default btn-xs" %></td>
      <td><%= grade.user.multipass_id %></td>
      <td><%= grade.score %></td>
      <td><%= grade.updated_at.localtime %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>

server/app/views/labs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Choose a Lab:</h1>
</br>
<div id="lab-btns">
  <% @labs.each do |lab| %>
    <% if lab.hidden%>
      <% if can? :toggle_hidden, lab %>
        <%= link_to lab.name, lab, class: "btn btn-warning btn-lg" %>
      <% end %>
    <% else %>
      <%= link_to lab.name, lab, class: "btn btn-default btn-lg" %>
    <% end %>
  <% end %>
</div>

<br>

server/app/views/labs/new.html.erb
<h1>New Lab</h1>

<%= render 'form' %>

<%= link_to 'Back', labs_path %>

server/app/views/labs/show.html.erb
<% provide(:title, @lab.name) %>

<p id="notice"><%= notice %></p>

<div>
  <h1 class="pull-left"><%= @lab.name %></h1>
  <div class="btn-group pull-right">
    <% if can? :toggle_hidden, @lab%>
      <% if @lab.hidden? %>
        <%= link_to 'Show To Students', labs_toggle_hidden_path, method: :post, class: "btn btn-danger" %>
      <% else %>
        <%= link_to 'Hide From Students', labs_toggle_hidden_path, method: :post, class: "btn btn-danger" %>
      <% end %>
    <% end %>
    <% if current_user.role == "admin" %>
      <%= link_to 'Edit', rails_admin.edit_path(model_name: 'lab', id: @lab.id), class: "btn btn-danger" %>
    <% end %>
    <% if can? :grades, @lab %>
      <%= link_to 'View Grades', labs_grades_path, class: "btn btn-danger" %>
    <% end %>
  </div>
</div>
<div class="clearfix"></div>
<% if @lab.due_date != nil %>
  <h5><%= @lab.due_date.localtime.strftime("Due on %B %d, %Y at %I:%M%p %Z") %></h5>
<% end %>
</br>
<% if !@lab.description.blank? %>
  <div class="well"><%= @lab.description %></div>
<% end %>
<p>
  <% @lab.assignments.each do |assignment| %>
  <%= link_to assignment.name, assignment, class: "btn btn-default btn-lg", 'data-no-turbolink' => true %>
  <% end %>
</p>